//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSQLviaADOCS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSQLviaADOCS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate column name.
        /// </summary>
        internal static string ERRMSG_DUPLICATE_COLUMN_NAME {
            get {
                return ResourceManager.GetString("ERRMSG_DUPLICATE_COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Amount Owed: {1}.
        /// </summary>
        internal static string MSG_COLUMN_LABEL_STRING_AMOUNT_OWED {
            get {
                return ResourceManager.GetString("MSG_COLUMN_LABEL_STRING_AMOUNT_OWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Amount Paid: {1}.
        /// </summary>
        internal static string MSG_COLUMN_LABEL_STRING_AMOUNT_PAID {
            get {
                return ResourceManager.GetString("MSG_COLUMN_LABEL_STRING_AMOUNT_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Comments: {1}{2}.
        /// </summary>
        internal static string MSG_COLUMN_LABEL_STRING_COMMENTS {
            get {
                return ResourceManager.GetString("MSG_COLUMN_LABEL_STRING_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Log: {1}.
        /// </summary>
        internal static string MSG_COLUMN_LABEL_STRING_LOG {
            get {
                return ResourceManager.GetString("MSG_COLUMN_LABEL_STRING_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Registrar ID: {1}.
        /// </summary>
        internal static string MSG_COLUMN_LABEL_STRING_REGISTRAR_ID {
            get {
                return ResourceManager.GetString("MSG_COLUMN_LABEL_STRING_REGISTRAR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Number {0,5}: Student ID: {1}.
        /// </summary>
        internal static string MSG_COLUMN_LABEL_STRING_STUDENT_ID {
            get {
                return ResourceManager.GetString("MSG_COLUMN_LABEL_STRING_STUDENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Transaction Number: {1}.
        /// </summary>
        internal static string MSG_COLUMN_LABEL_STRING_TRANSACTION_NUMBER {
            get {
                return ResourceManager.GetString("MSG_COLUMN_LABEL_STRING_TRANSACTION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnName = {0}, ColumnIndex = {1}, ColumnValue = {2}, ColumnLabel = {3}.
        /// </summary>
        internal static string MSG_COLUMNNAMESANDLABELS_TOSTRING {
            get {
                return ResourceManager.GetString("MSG_COLUMNNAMESANDLABELS_TOSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Exception HResult: {0}.
        /// </summary>
        internal static string MSG_EXCEPTION_HRESULT {
            get {
                return ResourceManager.GetString("MSG_EXCEPTION_HRESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Exception Source: {0}.
        /// </summary>
        internal static string MSG_EXCEPTION_SOURCE {
            get {
                return ResourceManager.GetString("MSG_EXCEPTION_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Exception StackTrace: {0}{1}.
        /// </summary>
        internal static string MSG_EXCEPTION_STACKTRACE {
            get {
                return ResourceManager.GetString("MSG_EXCEPTION_STACKTRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Exception TargetSite: {0}.
        /// </summary>
        internal static string MSG_EXCEPTION_TARGETSITE {
            get {
                return ResourceManager.GetString("MSG_EXCEPTION_TARGETSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An {0} exception arose.{2}{2}    Exception Message: {1}.
        /// </summary>
        internal static string MSG_EXCEPTION_TYPE_AND_MESSAGE {
            get {
                return ResourceManager.GetString("MSG_EXCEPTION_TYPE_AND_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing.
        /// </summary>
        internal static string MSG_LABEL_FOR_LISTING {
            get {
                return ResourceManager.GetString("MSG_LABEL_FOR_LISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table  .
        /// </summary>
        internal static string MSG_LABEL_FOR_TABLE {
            get {
                return ResourceManager.GetString("MSG_LABEL_FOR_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Listing record # {0}.
        /// </summary>
        internal static string MSG_PROGRESS_UPDATE {
            get {
                return ResourceManager.GetString("MSG_PROGRESS_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Name: Listing of everything in the Billing table{2}Run Date: {0} ({1} UTC){2}.
        /// </summary>
        internal static string MSG_REPORT_HEADER {
            get {
                return ResourceManager.GetString("MSG_REPORT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution succeeded..
        /// </summary>
        internal static string MSG_SHUTDOWN_NORMALLY {
            get {
                return ResourceManager.GetString("MSG_SHUTDOWN_NORMALLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution failed with status code {0:0x8x} ({1} decimal)..
        /// </summary>
        internal static string MSG_SHUTDOWN_WITH_ERROR {
            get {
                return ResourceManager.GetString("MSG_SHUTDOWN_WITH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} File Name = {2}.
        /// </summary>
        internal static string MSG_TASK_SUMMARY {
            get {
                return ResourceManager.GetString("MSG_TASK_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the RETURN key to return to Windows..
        /// </summary>
        internal static string MSG_WAIT_FOR_CARBON_UNIT {
            get {
                return ResourceManager.GetString("MSG_WAIT_FOR_CARBON_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of report, Total records = {0}.
        /// </summary>
        internal static string REPORT_FOOTER {
            get {
                return ResourceManager.GetString("REPORT_FOOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnName = {0}, ColumnLabel = {1}.
        /// </summary>
        internal static string UNIQUE_COLUMN_NAME_TOSTRING {
            get {
                return ResourceManager.GetString("UNIQUE_COLUMN_NAME_TOSTRING", resourceCulture);
            }
        }
    }
}
