//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSQLviaADOCS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\DAG\\Documents\\_Clients\\CodeProject Authors Group\\Actian Zen\\PSQLviaADOCS" +
            "_Billing_Detail.TXT")]
        public string BillingDetailReportFileName {
            get {
                return ((string)(this["BillingDetailReportFileName"]));
            }
            set {
                this["BillingDetailReportFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\DAG\\Documents\\_Clients\\CodeProject Authors Group\\Actian Zen\\PSQLviaADOCS" +
            "_Billing_Detail.TSV")]
        public string BillingDetailTabularReportFileName {
            get {
                return ((string)(this["BillingDetailTabularReportFileName"]));
            }
            set {
                this["BillingDetailTabularReportFileName"] = value;
            }
        }
    }
}
