//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSQLviaADOCS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\DAG\\Documents\\_Clients\\CodeProject Authors Group\\Actian Zen\\Table_Schema" +
            "s")]
        public string TableSchemasDirectoryName {
            get {
                return ((string)(this["TableSchemasDirectoryName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\DAG\\Documents\\_Clients\\CodeProject Authors Group\\Actian Zen\\Reports")]
        public string ReportsDirectoryName {
            get {
                return ((string)(this["ReportsDirectoryName"]));
            }
            set {
                this["ReportsDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$AssemblyTitle$$_$$TableName$$_Detail.TXT")]
        public string DetailReportListFileNameTemplate {
            get {
                return ((string)(this["DetailReportListFileNameTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$AssemblyTitle$$_$$TableName$$_Detail.TSV")]
        public string DetailTabularReportFileNameTemplate {
            get {
                return ((string)(this["DetailTabularReportFileNameTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=PervasiveOLEDB;Data Source=Demodata")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$AssemblyTitle$$_$$TableName$$_Properties.TSV")]
        public string TableColumnPropertiesFileNameTemplate {
            get {
                return ((string)(this["TableColumnPropertiesFileNameTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True;Yes;T;Y;Male;M")]
        public string BooleanTrueList {
            get {
                return ((string)(this["BooleanTrueList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False;No;F;N;Female;F")]
        public string BooleanFalseList {
            get {
                return ((string)(this["BooleanFalseList"]));
            }
        }
    }
}
